services:
  redis:
    container_name: redisc
    image: redis:7.4.5-alpine@sha256:bb186d083732f669da90be8b0f975a37812b15e913465bb14d845db72a4e3e08
    ports:
      - 6379:6379
    networks:
      - app

networks:
  app:
    driver: bridge 